<div class="spacer">&nbsp;</div>
<div id="footer">
<img src="images/car_berta.png"style="width:50px;height:43px;"/> &nbsp
<img src="images/car_main.png"style="width:50px;height:43px;"/> &nbsp
Tanankem & Loulou enterprise &nbsp
<img src="images/car_qtee.png"style="width:50px;height:43px;"/> &nbsp
<img src="images/car_sam.png"style="width:50px;height:43px;"/>
</div>

</div></div></div></div></div>
</body>
</html>