<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Microchip TCP/IP Stack Demo App</title>
<link href="/ourStyle.css" rel="stylesheet" type="text/css" />
<script src="/mchp.js" type="text/javascript"></script>
</head>

<body>
<div id="shadow-one"><div id="shadow-two"><div id="shadow-three"><div id="shadow-four">
<div id="title">
	<img src='images/QbertLogo.jpg' alt='logo' style="width:328px;height:120px;"/> 
</div>
<div id="page">

<!--<div style="padding:0 0 5px 5px"><img src="/mchp.gif" alt="Microchip" /></div>-->

<div id="menu">
	<a href="/index.htm">Overview</a>
	<a href="/show.htm">Real-time</a>
	<a href="/instructions.htm">Instructions</a>
	<a href="/records.htm">Records list</a>
	<a href="/codes.htm">Cheating codes</a>
</div>