# TCL File Generated by Component Editor 15.0
# Fri Apr 22 15:34:00 CEST 2016
# DO NOT MODIFY


# 
# LT_Avalon "LT_Avalon" v1.0
#  2016.04.22.15:34:00
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module LT_Avalon
# 
set_module_property DESCRIPTION ""
set_module_property NAME LT_Avalon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME LT_Avalon
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL LT_Avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file LT_Avalon.sv SYSTEM_VERILOG PATH ip/LT24_SPI/LT_Avalon.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter Data_0 STD_LOGIC_VECTOR 0
set_parameter_property Data_0 DEFAULT_VALUE 0
set_parameter_property Data_0 DISPLAY_NAME Data_0
set_parameter_property Data_0 TYPE STD_LOGIC_VECTOR
set_parameter_property Data_0 UNITS None
set_parameter_property Data_0 ALLOWED_RANGES 0:511
set_parameter_property Data_0 HDL_PARAMETER true
add_parameter Data_1 STD_LOGIC_VECTOR 1
set_parameter_property Data_1 DEFAULT_VALUE 1
set_parameter_property Data_1 DISPLAY_NAME Data_1
set_parameter_property Data_1 TYPE STD_LOGIC_VECTOR
set_parameter_property Data_1 UNITS None
set_parameter_property Data_1 ALLOWED_RANGES 0:511
set_parameter_property Data_1 HDL_PARAMETER true
add_parameter Data_2 STD_LOGIC_VECTOR 2
set_parameter_property Data_2 DEFAULT_VALUE 2
set_parameter_property Data_2 DISPLAY_NAME Data_2
set_parameter_property Data_2 TYPE STD_LOGIC_VECTOR
set_parameter_property Data_2 UNITS None
set_parameter_property Data_2 ALLOWED_RANGES 0:511
set_parameter_property Data_2 HDL_PARAMETER true
add_parameter Data_3 STD_LOGIC_VECTOR 3
set_parameter_property Data_3 DEFAULT_VALUE 3
set_parameter_property Data_3 DISPLAY_NAME Data_3
set_parameter_property Data_3 TYPE STD_LOGIC_VECTOR
set_parameter_property Data_3 UNITS None
set_parameter_property Data_3 ALLOWED_RANGES 0:511
set_parameter_property Data_3 HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave write_data writedata Input 32
add_interface_port avalon_slave read_data readdata Output 32
add_interface_port avalon_slave write write Input 1
add_interface_port avalon_slave read read Input 1
add_interface_port avalon_slave address address Input 8
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset reset
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end SPI_CS cs Input 1
add_interface_port conduit_end SPI_SDI sdi Input 1
add_interface_port conduit_end SPI_SDO sdo Output 1
add_interface_port conduit_end SPI_SCLK sclk Input 1
add_interface_port conduit_end SPI_INT sint Output 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint avalon_slave
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender IRQ_PTC irq Output 1

